### ISSUE TITLE
Not working IOS 13.3.1

### ISSUE THREAD

**Issue by yocase** [jakeajames/time_waste#1]
I though that this update would help jailbreak iOS 13.3.1, iPhone XR but I might just be confused. I politely request you to try to jailbreak iOS 13.3.1. Thank you
![C5210E49-AD75-4FB3-9D37-75F395EA96F6](https://user-images.githubusercontent.com/61461438/75248917-1ca3bd00-57a3-11ea-9a4c-0da0080004e4.png)

**Comment by jakeajames** [comment]
can you read?
