### ISSUE TITLE
iOS 12.4.1 iPhone XR kernel read fails

### ISSUE THREAD

**Issue by 3h6-1** [jakeajames/time_waste#5]
I tried running this 6 times and 4/6 times I get:
[i] Offsets selected for iOS 12.0 or above
[*] Initialized offsets
[*] Initialized IOAccelerator
[i] page size: 0x4000
[*] Initialized IOSurface
[*] Doing stage 0 heap setup
[*] Doing stage 1 heap setup
[*] Triggering bug with 7 bytes
[*] Corruption worked?
[*] Freed kmsg
[+] ikm_header leak: 0xffffffe124a18028
[+] Segment list calculated to be at: 0xffffffe1189f0000
[+] fakeport: 0x6907
[+] Leaked port: 0xffffffe004764540
[-] Kernel read failed!

And 2/6 times I get a bunch of these messages and they never end until I stop it in Xcode:
[-] Probably won't work with this timestamp, retrying...
[-] Probably won't work with this timestamp, retrying...
[-] Probably won't work with this timestamp, retrying...
[-] Probably won't work with this timestamp, retrying...
[-] Probably won't work with this timestamp, retrying...
[-] Probably won't work with this timestamp, retrying...

**Comment by jakeajames** [comment]
Remove all architectures except arm64e, I must have done something wrong that makes it not use the arm64e slice.
